<!DOCTYPE HTML>
<html>
  <head>
    <title>Todo</title>
    <link rel="stylesheet" href="/stylesheets/style.css">
  </head>
  <body>
    <h1><?= $title ?></h1>
    <form action="/todos" method="POST">
      <input type="text" name="content" />
      <input type="submit" value="新增" />
    </form>
    <ul>
        <?php foreach($todos as $todo): ?>
        <li><?= $todo->get('content') ?></li>
        <?php endforeach ?>
    </ul>
  </body>
</html>